@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":PatientBookParser" as PatientBookParser LOGIC_COLOR
participant ":AddMedicalEntryCommandParser" as AddMedicalEntryCommandParser LOGIC_COLOR
participant "cmd:AddMedicalEntryCommand" as AddMedicalEntryCommand LOGIC_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

[-> LogicManager : execute("...")
activate LogicManager


LogicManager -> AddressBookParser : parseCommand("...")
activate AddressBookParser


AddressBookParser -> PatientBookParser : parsePatientCommand("...")
activate PatientBookParser

PatientBookParser -> AddMedicalEntryCommandParser : parsePatientCommand(\ncommand, args)
activate AddMedicalEntryCommandParser
ref over AddMedicalEntryCommandParser: Parse user input

create AddMedicalEntryCommand
AddMedicalEntryCommandParser -> AddMedicalEntryCommand
activate AddMedicalEntryCommand

AddMedicalEntryCommand --> AddMedicalEntryCommandParser : cmd
deactivate AddMedicalEntryCommand
AddMedicalEntryCommandParser --> PatientBookParser : cmd
deactivate AddMedicalEntryCommandParser
AddMedicalEntryCommandParser -[hidden]-> AddressBookParser
destroy AddMedicalEntryCommandParser

PatientBookParser --> AddressBookParser : cmd
deactivate PatientBookParser
PatientBookParser -[hidden]-> AddressBookParser
destroy PatientBookParser

AddressBookParser --> LogicManager : cmd
deactivate AddressBookParser
AddressBookParser -[hidden]-> LogicManager
destroy AddressBookParser

LogicManager -> AddMedicalEntryCommand : execute(model)
activate AddMedicalEntryCommand

AddMedicalEntryCommand -> ModelManager : setPatient
activate ModelManager
ModelManager --> AddMedicalEntryCommand
deactivate ModelManager
AddMedicalEntryCommand -> ModelManager : updateAppointmentBook
activate ModelManager
ModelManager --> AddMedicalEntryCommand
deactivate ModelManager
AddMedicalEntryCommand -> ModelManager : updateFilteredPatientList
activate ModelManager
ModelManager --> AddMedicalEntryCommand
deactivate ModelManager
AddMedicalEntryCommand -> ModelManager : updateFilteredAppointmentList
activate ModelManager
ModelManager --> AddMedicalEntryCommand
deactivate ModelManager

create CommandResult
AddMedicalEntryCommand -> CommandResult
activate CommandResult

CommandResult --> AddMedicalEntryCommand : result
deactivate CommandResult

AddMedicalEntryCommand --> LogicManager : result
deactivate AddMedicalEntryCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
