@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":PrescriptionCommand" as PrescriptionCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "appointment:Appointment" as appointment MODEL_COLOR
participant "appointmentBook\n:AppointmentBook" as appointmentBook MODEL_COLOR
end box

[-> PrescriptionCommand : execute()

PrescriptionCommand -> Model : getAppointmentBook()

Model --> PrescriptionCommand : AppointmentBook


PrescriptionCommand -> Model : add/delete Prescription
Model -> appointment : getPrescription()
appointment --> Model : prescriptions


Model -> appointmentBook : setAppointment()
appointmentBook --> Model

Model ---> PrescriptionCommand

create CommandResult
PrescriptionCommand -> CommandResult
CommandResult ---> PrescriptionCommand : result

[<--PrescriptionCommand : result

@enduml
