@startuml
start
:User executes prescription command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command is valid])
    :Add/remove prescription
    from Appointment object;
    :Updates model;
    :Write to file;
else ([else])
    :Show error
    message to user;

endif
stop
@enduml
