@startuml
!include style.puml

Participant ":Logic" as logic LOGIC_COLOR
Participant ":Storage" as storage STORAGE_COLOR
Participant ":JsonUtil" as jsonutil USER_COLOR

box Model MODEL_COLOR_T1
participant ":Model" as model MODEL_COLOR
participant ":JsonAdaptedAppointment" as jaa MODEL_COLOR
participant ":Appointment" as appointment MODEL_COLOR
participant ":AddressBook" as addressbook MODEL_COLOR
end box

[-> logic: execute(anyCommand)

logic -> model : getAddressBook()

logic -> model : getAppointmentBook()

logic -> storage : saveAppointmentBook(appointmentBook, addressBook)

create jaa
storage -> jaa : JsonAdaptedAppointment()
jaa -> appointment : getPatient()
jaa -> addressbook : getIndexOfPatient(patient)

storage -> jsonutil : Save JSON File
@enduml
